---
openapi: 3.0.0
info:
  title: LibAPI
  description: Service Web
  version: 1.0.0
servers:
- url: http://localhost/projet
paths:
  /books:
    get:
      tags:
      - livre
      summary: affichage livre
      responses:
        "200":
          description: un tableau de livre
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Livre'
components:
  schemas:
    Livre:
      type: object
      properties:
        id:
          type: integer
          format: int64
