openapi: 3.0.0
info:
  version: 1.0.0
  title: LibAPI
  description: Service Web
  
servers: 
  - url: http://localhost/projet
paths:

  /books:
    get:
      tags:
        - livre
      summary: affichage livre
      responses:
        "200":
          description: un tableau de livre
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Livre'
  components:
    schemas:
      Livre:
        type: object
        properties:
          id:
            type: integer
            format: int64
  /books/{id}:
    get:
      tags: 
        - livre
      summary: affichage livre selon id
      parameters:
        - name: id
          in: path
          required:  true
          description: le id du livre a afficher
          schema:
            type: integer
      responses:
        '200':
          description: le livre a afficher
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Livre'
components:
  schemas:
    Livre:
      type: object
      required:
        - genreId
        - titre
        - isbn
      properties:
        id:
          type: integer
          format: int64
        genreId:
          type: integer
          format: int64
        titre:
          type: string
        isbn:
          type: string
      example:
          id: 1
          genreId : 1
          titre: Fondation
          isbn: '9782070463619'
    Livres:
      type: array
      items:
        $ref: '#/components/schemas/Livre'